INSERT INTO PUBLIC.CURRENCY (ID, NAME, CODE, RATE, CREATED_BY, CREATED_AT, UPDATE_BY, UPDATE_AT) VALUES (UUID(), 'Euro', 'EUR', 1, 'flyway', CURRENT_TIMESTAMP, 'flyway', CURRENT_TIMESTAMP);
INSERT INTO PUBLIC.CURRENCY (ID, NAME, CODE, RATE, CREATED_BY, CREATED_AT, UPDATE_BY, UPDATE_AT) VALUES (UUID(), 'US Dollar', 'USD', 0.75, 'flyway', CURRENT_TIMESTAMP, 'flyway', CURRENT_TIMESTAMP);
